project:
  type: book

book:
  title: "Documento de especificación de las pruebas de EEM"
  subtitle: Evaluación de estrategias de manejo pesquero (EEM) para el stock de anchoveta del norte de Chile en el contexto del enfoque precautorio de la Ley General de Pesca y Acuicultura. 
  author: "Natalia Opazo"

  sidebar:
    search: False
    border: true
    background: light 
    foreground: dark 
    style: floating 

  page-navigation: True 



  chapters:
    - part: index.qmd
      chapters: 
        - especie.qmd
    - metod.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



